name: VillagerNames
main: mn.frd.VillagerNames.VillagerNames
version: 0.5.1
website: http://frd.mn
author: frdmn
description: >
            Plugin to name villagers as soon as they spawn based on a dictionary
commands: 
  villagernames:
    description: Randomize the names of all loaded Villagers
    aliases: vn
    usage: /<command>
permissions:
  villagernames.randomize:
    default: op
  villagernames.rename:
    default: op